{
  "openapi": "3.0.0",
  "info": {
    "title": "API CONTACT MANAGEMENT",
    "description": "Api para gerencimanto de contatos",
    "termsOfService": "http://localhost:3333/terms",
    "contact": {
      "email": "lucas_morais_an@hotmail.com"
    },
    "verion": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:3333",
      "description": "API de test"
    },
    {
      "url": "https://contactsmanagement-backend-api.herokuapp.com/",
      "description": "API de produção"
    }
  ],
  "paths": {
    "/sessions": {
      "post": {
        "summary": "Autenticação do usuário",
        "description": "Essa rota é responsável para o usuário se autenticar na aplicação.",
        "tags": ["Session"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "items": {
                  "email": "lucas@gmail.com",
                  "password": "123456"
                }
              },
              "examples": {
                "session": {
                  "value":{
                    "email": "lucas@gmail.com",
                    "password": "123456"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Failed create session!"
          },
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Session"
                }
              }
            }
          }
        }
      }
    },
    "/user": {
      "get": {
        "summary": "Listagem de usuários",
        "description": "Essa rota é responsável por listar todos os usuários.",
        "tags": ["Users"],
        "security": [{ "bearerAuth": [] }],
        "responses": {
          "400": {
            "description": "Failed load to users!"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Users"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Cadastro de usuário",
        "description": "Essa rota é responsável por cadastrar um novo usuário.",
        "tags": ["Users"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "examples": {
                "user": {
                  "value":{
                    "name": "Lucas",
                    "lastname": "Knight",
                    "email": "lucas@gmail.com",
                    "password": "123456"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "401": {
            "description": "User already exists!"
          },
          "400": {
            "description": "Failed create user!"
          },
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          }
        }
      }
    },
    "/contacts": {
      "get": {
        "summary": "Listagem de contatos do usuário",
        "description": "Essa rota é responsável por listar os contatos salvos do usuário.",
        "tags": ["Contacts"],
        "security": [{ "bearerAuth": [] }],
        "responses": {
          "400": {
            "description": "Failed load to contacts!"
          },
          "401": {
            "description": "Unauthorized!"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Contact"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Cadastro de contato",
        "description": "Essa rota é responsável por cadastrar um novo contato.",
        "tags": ["Contacts"],
        "security": [{ "bearerAuth": [] }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Contact"
              },
              "examples": {
                "contact": {
                  "value":{
                    "name": "Kethilyn",
                    "lastname": "Ferreia",
                    "telephone": "00 98765-4321",
                    "birthdate": "15/04/2022",
                    "email": "kethelyn@gmail.com",
                    "street": "Palace",
                    "complement": "Casa",
                    "district": "Centro",
                    "city": "Recife",
                    "uf": "PE",
                    "user": "62573b8fb0494530aac646c6"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Failed create contact!"
          },
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Contact"
                }
              }
            }
          }
        }
      }
    },
    "/contacts/{id}": {
      "get": {
        "summary": "Buscar contato pelo id",
        "description": "Essa rota é responsável por buscar o contato pelo id.",
        "tags": ["Contacts"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Contato pelo ID.",
            "required": true
          }
        ],
        "security": [{ "bearerAuth": [] }],
        "responses": {
          "400": {
            "description": "Failed load to contacts!"
          },
          "401": {
            "description": "Unauthorized!"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "$ref": "#/components/schemas/Contact"
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "Alterar o contato pelo id",
        "description": "Essa rota é responsável por alterar os dados do contato pelo id.",
        "tags": ["Contacts"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Contato pelo ID.",
            "required": true
          }
        ],
        "security": [{ "bearerAuth": [] }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Contact"
              },
              "examples": {
                "contact": {
                  "value":{
                    "name": "Kethilyn",
                    "lastname": "Ferreia Brasil",
                    "telephone": "99 98765-4321",
                    "birthdate": "15/04/2000",
                    "email": "kethelyn@gmail.com",
                    "street": "Palace Country",
                    "complement": "Casa",
                    "district": "Centro",
                    "city": "Recife",
                    "uf": "PE",
                    "user": "62573b8fb0494530aac646c6"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Failed load to contact!"
          },
          "401": {
            "description": "Unauthorized!"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "$ref": "#/components/schemas/Contact"
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Deletar contato pelo id",
        "description": "Essa rota é responsável por deletar o contato por id.",
        "tags": ["Contacts"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Contato pelo ID.",
            "required": true
          }
        ],
        "security": [{ "bearerAuth": [] }],
        "responses": {
          "400": {
            "description": "Failed delete contact!"
          },
          "401": {
            "description": "Unauthorized!"
          },
          "200": {
            "description": "OK"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Session": {
        "type": "object",
        "properties": {
          "user": {
            "type": "object"
          },
          "token": {
            "type": "string"
          }
        }
      },
      "User": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "lastname": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "Users": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "lastname": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "createdAt": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          }
        }
      },
      "Contact": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "lastname": {
            "type": "string"
          },
          "telephone": {
            "type": "string"
          },
          "birthdate": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "street": {
            "type": "string"
          },
          "complement": {
            "type": "string"
          },
          "district": {
            "type": "string"
          },
          "city": {
            "type": "string"
          },
          "uf": {
            "type": "string"
          },
          "user": {
            "type": "string"
          }
        }
      }
    }
  },
  "securitySchemes": {
    "bearerAuth": {
      "type": "http",
      "scheme": "bearer",
      "bearerFormat": "JWT"
    }
  }
}

